version: '3'
services: 
  db:
    container_name: backend-portafolio-db
    image: mongo:5.0.16
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGODB_DATABASE: 
    volumes:
      - ./mongo:/data/db